### ISSUE TITLE
模型使用问题

### ISSUE THREAD

**Issue by zhuyu1326** [HieDean/phasen#1]
您好，有问题想请教一下。模型训练完成后，如何使用模型去处理其他新数据呢？换句话说是如何应用训练好的模型。

**Comment by HieDean** [comment]
> 您好，有问题想请教一下。模型训练完成后，如何使用模型去处理其他新数据呢？换句话说是如何应用训练好的模型。

可以使用`./tools/denoise_test.py`对一个目录下的所有文件进行处理，使用前先确保`./tools/denoise_test.py`文件中的参数、路径等是你想要的。

**Comment by zhuyu1326** [comment]
您好有一个新问题，我这面数据处理的顺序是resample然后clip的，参数没有改动过，训练时梯度爆炸导致loss溢出，打印如下：
 
请问需要如何解决这个问题。谢谢了



| |
朱禹
|
|
邮箱：zhuyu1326@126.com
|
在2020年07月20日 18:25，HieDean 写道：

您好，有问题想请教一下。模型训练完成后，如何使用模型去处理其他新数据呢？换句话说是如何应用训练好的模型。

可以使用./tools/denoise_test.py对一个目录下的所有文件进行处理，使用前先确保./tools/denoise_test.py文件中的参数、路径等是你想要的。

**Comment by HieDean** [comment]
Emmmmmmm，这个问题我也出现过，我当时的情况是正常训练一段时间后突然nan，然后我给你几个我的想法吧，应该都可以对梯度爆炸起一些改善作用
1.修改超参数，比如lr改小一点（估计没啥用）
2.原论文中对网络结构有很多细节没有描述的很清楚，有一些是我凭自己理解写的，你可以参照原论文再改一改，比如gln层的顺序，最开始到底需不需要bn之类的
3.原论文中的loss函数比较奇怪，关于损失函数我是参照[http://github.com/huyanxin/phasen](http://github.com/huyanxin/phasen)实现的，但这个实现不一定对，我自己也写了一些其他的loss的实现方式你可以参考一下，或者根据自己的理解改一改loss（别/0就行）

**Comment by yihe1003** [comment]
作者代码里有几个开根号的里面没有加一个很小的数保护，在0处根号运算不可微分，导致训练的时候出现NAN
