### ISSUE TITLE
延长音频问题

### ISSUE THREAD

**Issue by chaoxiaoxiacxx** [HieDean/phasen#2]
您好，我正在修改代码，关于音频必须限制为tensor格式，不然torch无法处理，因此只能更改为1s的问题，想问一下如何可以延长一下音频时间嘛

**Comment by HieDean** [comment]
> 您好，我正在修改代码，关于音频必须限制为tensor格式，不然torch无法处理，因此只能更改为1s的问题，想问一下如何可以延长一下音频时间嘛

代码里把训练用的音频时长设置为1s是因为vbd这个数据集中没有短于1s的音频文件，这与torch、tensor无关。训练用的音频时长可以在`tools/clip.py`中指定。
另外，phasen的原文中是使用3s的音频进行训练，对于vbd数据集中长度不足3s的音频文件可以采取补0或丢弃的方法。

**Comment by chaoxiaoxiacxx** [comment]
哇哦，非常感谢！受益匪浅
